### ISSUE TITLE
SyncBatchNorm

### ISSUE THREAD

**Issue by trevor-taeyeop** [youtubevos/MaskTrackRCNN#32]
I used the mmdetection from  **f3a939f**
It seems like torch 0.4.1 don't support the SynBatchNorm Libraray which is in the mmdetection part.

**Can I ask the how to handle SyncBatchNorm.** 

AttributeError: module 'torch.nn' has no attribute 'SyncBatchNorm'

https://github.com/open-mmlab/mmdetection/blob/8732ed96a85163fc4fb6d36b52ff3c3d25172611/tools/fuse_conv_bn.py#L32

https://github.com/open-mmlab/mmdetection/issues/684

>  python3 tools/test_video.py configs/masktrack_rcnn_r50_fpn_1x_youtubevos.py models/epoch_12.pth --out output --eval segm
> 
> Traceback (most recent call last):
>   File "tools/test_video.py", line 4, in <module>
>     import mmcv
>   File "/home/user/anaconda3/envs/MaskTrackRCNN/lib/python3.6/site-packages/mmcv/__init__.py", line 4, in <module>
>     from .fileio import *
>   File "/home/user/anaconda3/envs/MaskTrackRCNN/lib/python3.6/site-packages/mmcv/fileio/__init__.py", line 4, in <module>
>     from .io import dump, load, register_handler
>   File "/home/user/anaconda3/envs/MaskTrackRCNN/lib/python3.6/site-packages/mmcv/fileio/io.py", line 4, in <module>
>     from ..utils import is_list_of, is_str
>   File "/home/user/anaconda3/envs/MaskTrackRCNN/lib/python3.6/site-packages/mmcv/utils/__init__.py", line 8, in <module>
>     from .parrots_wrapper import (CUDA_HOME, BuildExtension, CppExtension,
>   File "/home/user/anaconda3/envs/MaskTrackRCNN/lib/python3.6/site-packages/mmcv/utils/parrots_wrapper.py", line 67, in <module>
>     _BatchNorm, _InstanceNorm, SyncBatchNorm_ = _get_norm()
>   File "/home/user/anaconda3/envs/MaskTrackRCNN/lib/python3.6/site-packages/mmcv/utils/parrots_wrapper.py", line 60, in _get_norm
>     SyncBatchNorm_ = torch.nn.SyncBatchNorm
> AttributeError: module 'torch.nn' has no attribute 'SyncBatchNorm'
>

**Comment by trevor-taeyeop** [comment]
solved changing mmcv version
