### ISSUE TITLE
Error during test

### ISSUE THREAD

**Issue by danperazzo** [youtubevos/MaskTrackRCNN#34]
Hello, thanks for releasing the code! I have been having trouble initializing this code, I have performed the installation as mentioned on the README.md. But I encountered the following error:
`Traceback (most recent call last):
  File "tools/test_video.py", line 4, in <module>
    import mmcv
  File "/home/daniel/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/daniel/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/mmcv/fileio/__init__.py", line 4, in <module>
    from .io import dump, load, register_handler
  File "/home/daniel/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/mmcv/fileio/io.py", line 4, in <module>
    from ..utils import is_list_of, is_str
  File "/home/daniel/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/mmcv/utils/__init__.py", line 29, in <module>
    from .parrots_wrapper import (CUDA_HOME, BuildExtension, CppExtension,
  File "/home/daniel/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/mmcv/utils/parrots_wrapper.py", line 79, in <module>
    _BatchNorm, _InstanceNorm, SyncBatchNorm_ = _get_norm()
  File "/home/daniel/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/mmcv/utils/parrots_wrapper.py", line 71, in _get_norm
    SyncBatchNorm_ = torch.nn.SyncBatchNorm
AttributeError: module 'torch.nn' has no attribute 'SyncBatchNorm'

Thank you for your attention!
`

**Comment by danperazzo** [comment]
Solved with [this issue](https://github.com/youtubevos/MaskTrackRCNN/issues/32)
