### ISSUE TITLE
Roi pulling not recognized!

### ISSUE THREAD

**Issue by peymanbateni** [youtubevos/MaskTrackRCNN#36]
I get the following error when running evaluation:

Traceback (most recent call last):
  File "./tools/test_video.py", line 8, in <module>
    from mmdet import datasets
  File "/home/bigboi/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/mmdet/datasets/__init__.py", line 1, in <module>
    from .custom import CustomDataset
  File "/home/bigboi/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 11, in <module>
    from .extra_aug import ExtraAugmentation
  File "/home/bigboi/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/mmdet/datasets/extra_aug.py", line 5, in <module>
    from mmdet.core.evaluation.bbox_overlaps import bbox_overlaps
  File "/home/bigboi/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/bigboi/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/home/bigboi/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/home/bigboi/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/mmdet/ops/__init__.py", line 2, in <module>
    from .roi_align import RoIAlign, roi_align
  File "/home/bigboi/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/mmdet/ops/roi_align/__init__.py", line 1, in <module>
    from .functions.roi_align import roi_align
  File "/home/bigboi/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/mmdet/ops/roi_align/functions/roi_align.py", line 3, in <module>
    from .. import roi_align_cuda
ImportError: cannot import name 'roi_align_cuda' from 'mmdet.ops.roi_align' (/home/bigboi/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/mmdet/ops/roi_align/__init__.py)

**Comment by peymanbateni** [comment]
System debugging resolved the problem!

**Comment by bo-miao** [comment]
I met the same problem, may I know more details about solving this issue? Thanks.
