### ISSUE TITLE
TypeError: optimizer must be a dict of torch.optim.Optimizers, but optimizer["type"] is a <class 'str'>

### ISSUE THREAD

**Issue by qzsrh** [youtubevos/MaskTrackRCNN#51]
When I started training the model, the errors are as follows:

Traceback (most recent call last):

File "tools/train.py", line 90, in <module>

main()

File "tools/train.py", line 86, in main

logger=logger)

File "/home/zhangsai/.conda/envs/VIS/lib/python3.6/site-packages/mmdet/apis/train.py", line 59, in train_ detector

_ non_ dist_ train(model, dataset, cfg, validate=validate)

File "/home/zhangsai/.conda/envs/VIS/lib/python3.6/site-packages/mmdet/apis/train.py", line 113, in _ non_ dist_ train

cfg.log_ level)

File "/home/zhangsai/.conda/envs/VIS/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 187, in __ init__

super().__ init__ (*args, **kwargs)

File "/home/zhangsai/.conda/envs/VIS/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 84, in __ init__

f'optimizer must be a dict of torch.optim.Optimizers, '

TypeError: optimizer must be a dict of torch.optim.Optimizers, but optimizer["type"] is a <class 'str'>
Hope to get your reply！

**Comment by linhaoqi027** [comment]
I have same problem.
