### ISSUE TITLE
undefined symbol: cudaLaunchKernel

### ISSUE THREAD

**Issue by zhw2020913** [youtubevos/MaskTrackRCNN#52]
Does anyone have this problem? Please help me answer

Traceback (most recent call last):
  File "tools/test_video.py", line 8, in <module>
    from mmdet import datasets
  File "/usr/local/lib/python3.8/dist-packages/mmdet/datasets/__init__.py", line 1, in <module>
    from .custom import CustomDataset
  File "/usr/local/lib/python3.8/dist-packages/mmdet/datasets/custom.py", line 11, in <module>
    from .extra_aug import ExtraAugmentation
  File "/usr/local/lib/python3.8/dist-packages/mmdet/datasets/extra_aug.py", line 5, in <module>
    from mmdet.core.evaluation.bbox_overlaps import bbox_overlaps
  File "/usr/local/lib/python3.8/dist-packages/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/usr/local/lib/python3.8/dist-packages/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/usr/local/lib/python3.8/dist-packages/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/usr/local/lib/python3.8/dist-packages/mmdet/ops/__init__.py", line 1, in <module>
    from .nms import nms, soft_nms
  File "/usr/local/lib/python3.8/dist-packages/mmdet/ops/nms/__init__.py", line 1, in <module>
    from .nms_wrapper import nms, soft_nms
  File "/usr/local/lib/python3.8/dist-packages/mmdet/ops/nms/nms_wrapper.py", line 4, in <module>
    from .gpu_nms import gpu_nms
ImportError: /usr/local/lib/python3.8/dist-packages/mmdet/ops/nms/gpu_nms.cpython-38-x86_64-linux-gnu.so: undefined symbol: cudaLaunchKernel

**Comment by cuizoe-github** [comment]
I have the same problem, have you solved it

**Comment by cuizoe-github** [comment]
I have the same problem, have you solved it？

**Comment by NoMoreBeauty** [comment]
too

**Comment by SoftSisterRui** [comment]
I have the same problem, have you solved it？
